<?php
namespace Krausv\PermissionsPanel;

?>

<h1>Permissions panel</h1>
<div class="tracy-inner">
		<?php foreach ($resources as $resource):?>
			<h2 title="Resource <?=$resource?>"><?=$resource?></h2>
			<?php $tmp = $permissions["byResource"][$resource]; ?>
			<table>
			<tr>
			<th>Role</th>
			<th>Privileges</th>
			</tr>
			<?php foreach ($roles as $role):?>
				<?php if (array_key_exists($role, $tmp["byRole"])): ?>
					<tr>
						<td><?=$role?></td>
							<td>
							<?php foreach($tmp["byRole"][$role]["byPrivilege"] as $key => $allow): ?>
								<?=$key ?>,
							<?php endforeach ?>
							</td>
						</tr>
				<?php endif ?>
				<?php endforeach ?>
			</table>
	<?php endforeach ?>

</div>